name: Check envs
run-name: Let's check our variables
on:
  push:
    branches:
      - github-actions-learning
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_HOST: ${{secrets.VITE_API_HOST}}
      VITE_VERIFICATION_CODE: ${{secrets.VITE_VERIFICATION_CODE}}
    steps:
      - name: check env variables
        run: |
          echo "Let's check our environment variables"
          echo "VITE_API_HOST is $VITE_API_HOST"
          echo "VITE_VERIFICATION_CODE is $VITE_VERIFICATION_CODE"

